services:
  mongodb:
    image: mongo:7.0-rc
    # Remove verbose logging of mongodb image by sending logs to the void
    command: --quiet --logpath /dev/null 
    restart: always
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
  expressjs:
    depends_on:
      - mongodb
    volumes:
      - .:/app
    build: .
    restart: always
    ports:
      - 5000:5000
    stdin_open: true
    tty: true

volumes:
  db: