services:
    mongodb:
        image: mongo:7.0-rc
        # Remove verbose logging of mongodb image by sending logs to the void
        command: --quiet --logpath /dev/null
        restart: always
        ports:
            - 27017:27017
        volumes:
            - db:/data/db
    express:
        depends_on:
            - mongodb
        volumes:
            - .:/app
            - .env.development:/app/.env.development
            - /app/node_modules/ # Prevents node_modules from being overwritten by the volume
        env_file:
            - .env.development
        build: .
        restart: always
        ports:
            - 5000:5000
        stdin_open: true
        tty: true

volumes:
    db:
